# This is a basic workflow to help you get started with Actions

name: Deploy skills to CPANEL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
    - run: npm run build
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with: 
        server: ftp.joshuaogwang.com
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
